---
- include: playbooks/common.yml
- include: playbooks/bastion.yml
  when: role == "bastion"
- include: playbooks/backend.yml
  when: role == "backend"
- include: playbooks/frontend.yml
  when: role == "frontend"
