---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: Create a folder
  file:
    path: /tmp/fefiles
    state: directory

- name: Copy frontend file from s3
  command: aws s3 cp "{{ frontend_s3_filepath }}" "/tmp/fefiles/frontend.zip"

- name: Clean /var/www/html
  file:
    path: /var/www/html/
    state: absent

- name: Create /var/www/html
  file:
    path: /var/www/html/
    state: directory

- name: Extract frontend file
  unarchive:
    src: "/tmp/fefiles/frontend.zip"
    dest: /var/www/html/

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Delete frontend temp folder
  file:
    path: /tmp/fefiles
    state: absent
  
- name: Add user 'test'
  user:
    name: test
    group: sudo
    system: no

- name: Delete user 'test'
  user:
    name: test
    state: absent
    remove: yes
